### ISSUE TITLE
Update timeline inquiry

### ISSUE THREAD

**Issue by LadyHaley** [La1m1e/VelocityPersistent#1]
Hello, I was wondering if you had any solid plans for when you'd go back to finish the fallback system for this plugin?

**Comment by La1m1e** [comment]
Hello. I wasn't really working on it since then, but you can try to add servers to "try" in velocity.toml to act as a fallback. However in current state such servers would also be recorded as player default server. All plugins i've made were made for my server and needs, so currently im not planning on modifying them. However feel free to fork and make pushes if you do it. However im not entirely sure, as the existing codebase is not optimal (just bad). As that was the first plugin i did
